FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# evolAPI

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite Machine Learning language?",
                "choices": [
                    {
                        "choice": "Matlab",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "R",
                        "votes": 512
                    }, {
                        "choice": "TensorFlow",
                        "votes": 256
                    }
                ]
            }
        ]